<h2>Categorias</h2>
<ul>
    <?php foreach($categories as $categorie): ?>
        <li>
            <?=$categorie->nombre_categoria?>
            <span><a href='categorieById/<?=$categorie->id_categoria?>' type='button'>Detalle</a></span>
        </li>
    <?php endforeach?>
</ul>

<form action="addCategorie" method="POST">
    <div>
        <label>TIPO DE PRENDA</label>
        <input type="text" name="nombre_categoria" placeholder="Ingrese la categoria" required>
    </div>
    <button type="submit">Agregar Categoria</button>
</form>