<?php if (isset($_SESSION['user'])): ?>
    <form action="addProduct" method="POST" class="mt-6 bg-white p-4 rounded-lg shadow">
        <div>
            <label class="block text-sm font-medium">PRODUCTO</label>
            <input type="text" name="tipo" required class="mt-1 block w-full border border-gray-300 rounded-md p-2 focus:ring-2 focus:ring-blue-500">
            
            <label class="block text-sm font-medium">PRECIO</label>
            <input type="text" name="precio" required class="mt-1 block w-full border border-gray-300 rounded-md p-2 focus:ring-2 focus:ring-blue-500">

            <label for="categoria">Categoría:</label>
            <select name="id_categoria" id="categoria" required>
                <?php foreach ($categorias as $categoria): ?>
                    <option value="<?= $categoria->id_categoria ?>"><?= $categoria->nombre_categoria ?></option>
                <?php endforeach; ?>
            </select>        
        </div>
        <button type="submit" class="mt-4 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition">Agregar Producto</button>
    </form>
<?php endif; ?> 
