<h2>Productos</h2>
<ul>
    <?php foreach($products as $product): ?>
        <li>
            <strong>Tipo</strong>
            <?=$product->tipo?>
    
            <strong>Precio</strong>
            <?=$product->precio?>

            <strong>Detalles</strong>
            <span><a href='details/<?=$product->id_producto?>' type='button'>Detalle</a></span>
        </li>
    
    <?php endforeach?>
</ul>