<?php require './templates/header.phtml'; ?>

<h2>Detalles de la categoría</h2>

<?php if ($categorieById): ?>
    <strong>Nombre: </strong> <?= $categorieById->nombre_categoria ?>
<?php else: ?>
    <strong>No se encontró la categoría.</strong>
<?php endif; ?>

<!-- Lista de productos que pertenecen a la categoría seleccionada -->
<?php if (isset($products) && !empty($products)): ?>
    <h2>Productos de la categoría seleccionada</h2>
    <ul>
        <?php foreach($products as $product): ?>
            <li>
                Nombre: <?= $product->nombre_producto ?> <br>
                Precio: <?= $product->precio ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>No hay productos en esta categoría.</p>
<?php endif; ?>

<?php require './templates/footer.phtml'; ?>
